language: node_js
node_js:
  - node
script:
  - npm run build
    
deploy:
  provider: s3
  access_key_id: "AKIAYCT2D5S5FFNJFVFW"
  secret_access_key: "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"
  bucket: "single-spa-test"
  region: "ap-southeast-1"
  cache-control: "max-age=31536000"
  acl: "public_read"
  local_dir: dist
  skip_cleanup: true
  on:
    branch: master